# Generated by Django 3.0.3 on 2020-06-12 19:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComparisonInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smartphone_one', models.CharField(max_length=50)),
                ('smartphone_two', models.CharField(max_length=50)),
                ('title', models.TextField(max_length=200)),
                ('intro', models.TextField(max_length=1000)),
                ('overview', models.TextField(max_length=1000)),
                ('display', models.TextField(max_length=1200)),
                ('design', models.TextField(max_length=1200)),
                ('performance', models.TextField(max_length=1000)),
                ('camera', models.TextField(max_length=1200)),
                ('battery', models.TextField(max_length=1200)),
                ('software', models.TextField(max_length=1200)),
                ('extras', models.TextField(max_length=1200)),
                ('conclusion', models.TextField(max_length=1200)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.TextField(max_length=300)),
                ('para1', models.TextField(max_length=1200)),
                ('para2', models.TextField(max_length=1200)),
                ('para3', models.TextField(max_length=1200)),
                ('conclusion', models.TextField(max_length=1200)),
                ('article_pic1', models.ImageField(blank=True, upload_to='')),
                ('article_pic2', models.ImageField(blank=True, upload_to='')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SmartphonesInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smartphone', models.TextField(max_length=50)),
                ('title', models.TextField(max_length=200)),
                ('intro', models.TextField(max_length=1000)),
                ('overview', models.TextField(max_length=1000)),
                ('display', models.TextField(max_length=1200)),
                ('design', models.TextField(max_length=1200)),
                ('performance', models.TextField(max_length=1000)),
                ('camera', models.TextField(max_length=1200)),
                ('battery', models.TextField(max_length=1200)),
                ('software', models.TextField(max_length=1200)),
                ('extras', models.TextField(max_length=1200)),
                ('conclusion', models.TextField(max_length=1200)),
                ('display_pic', models.ImageField(blank=True, upload_to='')),
                ('design_pic', models.ImageField(blank=True, upload_to='')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.TextField(max_length=50)),
                ('middlename', models.TextField(blank=True, max_length=50)),
                ('lastname', models.TextField(blank=True, max_length=50)),
                ('contact', models.PositiveIntegerField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SmartphoneComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_comment', models.BooleanField(default=False)),
                ('smartphone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smart_comments', to='idroidos.SmartphonesInfo')),
            ],
        ),
        migrations.CreateModel(
            name='NewsComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_comment', models.BooleanField(default=False)),
                ('smartphone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_comments', to='idroidos.NewsArticle')),
            ],
        ),
        migrations.CreateModel(
            name='ComparisonComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_comment', models.BooleanField(default=False)),
                ('smartphone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparison_comments', to='idroidos.ComparisonInfo')),
            ],
        ),
    ]
