# Generated by Django 3.0.3 on 2020-06-19 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idroidos', '0004_auto_20200619_0539'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparisoninfo',
            name='extra_pic',
            field=models.ImageField(blank=True, upload_to='comparisons'),
        ),
        migrations.AddField(
            model_name='smartphonesinfo',
            name='extra_pic',
            field=models.ImageField(blank=True, upload_to='smartphones'),
        ),
    ]
